"""v2 builder audit layers (spec §6) as regression tests. Six layers:

  1. byte-identity within cluster x carrier x gap x arm (wrapper residue)
  2. ban-list v2 over c1-c5 wrappers (phrase-level)
  3. witness token exactly once per assembled prompt
  4. bound adverbial only in bound-form cells
  5. v1-containment byte-diff: regenerating at eval-date 2026-08-11 and
     projecting onto the v1 schema must reproduce data/stimuli_v1.jsonl
     exactly (all 1,400 rows, byte-identical JSON)
  6. witness contamination: data/witness_contamination_check.json must exist
     and show <=5 corpus occurrences per witness (generated by
     tools/check_contamination.py; test SKIPS loudly until it exists —
     running it is a pre-freeze blocker, not a code failure)

Plus: global witness-token uniqueness across frames (placebo protocol
requires cross-witness hits to be meaningful) and gap-date arithmetic.
"""
import json
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))
from build_stimuli_v2 import (BAN_V2, CARRIERS, GAP_OFFSETS, bound_label,  # noqa: E402
                              bound_month_of, build, frames_v2, session_date,
                              v1_view)
import datetime as dt  # noqa: E402

EVAL = "2026-08-11"


@pytest.fixture(scope="module")
def cases():
    return build(EVAL)


@pytest.fixture(scope="module")
def frames():
    return frames_v2()


def test_audit1_wrapper_byte_identity(cases, frames):
    groups = {}
    for c in cases:
        # locate the key line by witness-token position within the history;
        # the residue outside that line (plus the query) must be identical
        # across forms/lexemes/subjects within the group
        hist = c["history"]
        idx = hist.find(c["wit_token"])
        assert idx >= 0
        # find enclosing line
        start = hist.rfind("\n", 0, idx) + 1
        end = hist.find("\n", idx)
        end = len(hist) if end == -1 else end
        line = hist[start:end]
        # within the line, the key line is a contiguous span; replace the
        # whole line with a marker plus the line's constant prefix/suffix is
        # frame-dependent, so compare (line-with-token removed) at group
        # level instead: the residue outside the key line's LINE plus query
        residue = hist[:start] + "<KEYLINE>" + hist[end:] + "\x00" + c["query"]
        g = (c["frame"], c["cluster"], c["carrier"], c["gap"], c["arm"])
        groups.setdefault(g, set()).add(
            (residue, line.count(c["wit_token"])))
    bad = [g for g, r in groups.items() if len({x[0] for x in r}) != 1]
    assert not bad, bad[:5]


def test_audit2_ban_list_c1_c5_wrappers(cases, frames):
    for c in cases:
        if c["carrier"] == "c0_original":
            continue
        hist = c["history"]
        idx = hist.find(c["wit_token"])
        start = hist.rfind("\n", 0, idx) + 1
        end = hist.find("\n", idx)
        end = len(hist) if end == -1 else end
        line = hist[start:end]
        # wrapper = the carrier text minus the key line; key line is inside
        # the line, so strip the whole witness line's key sentence by
        # removing the templated span: conservatively test the residue
        # around the line
        wrapper = hist[:start] + hist[end:]
        hit = BAN_V2.search(wrapper)
        assert not hit, (c["case_id"], hit.group(0))


def test_audit2_ban_applies_to_carrier_templates():
    for name, tmpl in CARRIERS.items():
        wrapper = tmpl.replace("{k}", "")
        hit = BAN_V2.search(wrapper)
        assert not hit, (name, hit.group(0))


def test_audit3_witness_exactly_once(cases):
    for c in cases:
        assert (c["history"] + c["query"]).count(c["wit_token"]) == 1, \
            c["case_id"]


def test_audit4_bound_adverbial_only_in_bound_cells(cases):
    for c in cases:
        has_until = "until" in c["history"].lower()
        if c["form"] == "bound":
            assert has_until, c["case_id"]
        else:
            assert not has_until, c["case_id"]


def test_audit5_v1_containment_byte_diff(cases):
    v1_lines = [ln for ln in
                (ROOT / "data" / "stimuli_v1.jsonl").read_text().splitlines()
                if ln.strip()]
    assert len(v1_lines) == 1400
    projected = {}
    for c in cases:
        v = v1_view(c)
        if v is not None:
            s = json.dumps(v, ensure_ascii=False)
            assert v["case_id"] not in projected, ("duplicate projection",
                                                   v["case_id"])
            projected[v["case_id"]] = s
    assert len(projected) == 1400, len(projected)
    v1_by_id = {json.loads(ln)["case_id"]: ln for ln in v1_lines}
    mismatches = []
    for cid, s in projected.items():
        if v1_by_id.get(cid) != s:
            mismatches.append(cid)
    assert not mismatches, (len(mismatches), mismatches[:5])


def test_audit6_contamination_check_result():
    """<=5 corpus occurrences is a HARD gate only for the NEW frames (their
    witnesses are replaceable pre-freeze). The frozen v1 witnesses violate
    it structurally — vehicle strings are real car descriptions, household
    witnesses are bare first names — and are containment-locked, so they are
    disclosure items (build notes / datasheet), not failures. Checked
    2026-08-12: equipment 0/20 over, project 0/20, affiliate_role 0/20
    after replacing Thornbeck->Vearnholt."""
    path = ROOT / "data" / "witness_contamination_check.json"
    if not path.exists():
        pytest.skip("PRE-FREEZE BLOCKER: run tools/check_contamination.py "
                    "to generate data/witness_contamination_check.json")
    data = json.loads(path.read_text())
    new_frames = ("equipment", "affiliate_role", "project")
    over = {w: r["counts"] for w, r in data["witnesses"].items()
            if r["frame"] in new_frames and r["over"]}
    assert not over, over
    # every current new-frame witness must actually be in the check file
    frames = frames_v2()
    checked = set(data["witnesses"])
    missing = [w for f in new_frames for w in frames[f]["witnesses"]
               if w not in checked]
    assert not missing, missing


def test_global_token_uniqueness(frames):
    tokens = []
    for spec in frames.values():
        tokens.extend(t.lower() for t in spec["wit_token"])
    assert len(tokens) == len(set(tokens)), "witness token collision"


def test_gap_date_arithmetic():
    eval_d = dt.date(2026, 8, 11)
    assert session_date(eval_d, "fresh") == dt.date(2026, 8, 9)     # v1 fresh
    assert session_date(eval_d, "stale") == dt.date(2025, 12, 9)    # v1 stale
    assert session_date(eval_d, "near") == dt.date(2026, 6, 30)
    assert session_date(eval_d, "boundary") == dt.date(2026, 6, 12)
    assert session_date(eval_d, "stale_long") == dt.date(2025, 6, 12)
    # boundary: bound month first day must be AFTER eval (still valid)
    s = session_date(eval_d, "boundary")
    y, m = bound_month_of(s)
    assert dt.date(y, m, 1) > eval_d
    # expired_soon: bound first day must be BEFORE eval by 7-40 days
    s = session_date(eval_d, "expired_soon")
    y, m = bound_month_of(s)
    delta = (eval_d - dt.date(y, m, 1)).days
    assert 7 <= delta <= 40, delta


def test_bound_month_never_dec_jan():
    for month in range(1, 13):
        s = dt.date(2026, month, 9)
        _, m = bound_month_of(s)
        assert m not in (12, 1), (month, m)


def test_bound_label_year_qualified_iff_cross_year():
    lab, _ = bound_label(dt.date(2026, 8, 9))     # +3 -> November 2026
    assert lab == "November"
    lab, _ = bound_label(dt.date(2025, 12, 9))    # Dec+3 -> March 2026
    assert lab == "March 2026"


def test_run_allocation_counts(cases):
    per = {}
    for c in cases:
        per[c["component"]] = per.get(c["component"], 0) + 1
    assert per["e1_primary"] == 256
    assert per["e1_fresh_gate"] == 128
    assert per["e1_boundary"] == 256
    assert per["carrier_e1"] == 400
    assert per["carrier_behavioral_p2"] == 160
    assert per["carrier_fresh_p3"] == 80
    assert per["behavioral_core"] == 960
    assert per["behavioral_boundary"] == 480
    assert per["anchor"] == 960
    assert per["explicit"] == 96
    assert per["l2"] == 256
    assert per["lexeme_subject"] == 144  # 9 felicitous combos × 16cl (freeze decision 2026-08-12)
    assert per["gap_gradient"] == 1080
    assert per["perf"] == 240
    assert per["v1_grid_extra"] == 420
    assert len(per) == 15  # any new component must be asserted here


def test_downstream_query_scoping(cases):
    # audit catch 2026-08-12: downstream_query marks exactly the rows that
    # spawn a derived run call (e2 from e1_primary, l2e2 from l2 = 512) plus
    # v1_grid_extra e1/l2 rows (containment schema only, never run)
    run_derived = [c for c in cases if "downstream_query" in c
                   and c["component"] != "v1_grid_extra"]
    assert len(run_derived) == 512
    assert {c["component"] for c in run_derived} == {"e1_primary", "l2"}
    for c in cases:
        if c["component"] == "v1_grid_extra" and c["arm"] in ("e1", "l2"):
            assert "downstream_query" in c, c["case_id"]


def test_gap_guards_reject_invalid_eval_dates():
    # audit catch 2026-08-12: Jan/early-Feb/late-Dec eval dates make
    # expired_soon land 41-98d past the bound; Mar-1/Apr-1 make boundary
    # degenerate. session_date must fail loudly, not emit incoherent cells.
    with pytest.raises(AssertionError):
        session_date(dt.date(2026, 1, 3), "expired_soon")
    with pytest.raises(AssertionError):
        session_date(dt.date(2026, 12, 20), "expired_soon")
    with pytest.raises(AssertionError):
        session_date(dt.date(2027, 3, 1), "boundary")


def test_gap_rules_hold_at_other_valid_eval_dates():
    for eval_d in (dt.date(2026, 2, 10), dt.date(2026, 8, 11),
                   dt.date(2026, 11, 5)):
        s = session_date(eval_d, "boundary")
        y, m = bound_month_of(s)
        assert dt.date(y, m, 1) > eval_d
        s = session_date(eval_d, "expired_soon")
        y, m = bound_month_of(s)
        assert 7 <= (eval_d - dt.date(y, m, 1)).days <= 40


def test_anchor_option_order_alternates(cases):
    # audit catch 2026-08-12: fixed SEND-first order = primacy bias in the
    # predicted direction; order alternates by cluster parity
    anchors = [c for c in cases if c["arm"] == "anchor"]
    assert anchors
    for c in anchors:
        send_first = c["query"].index("ACTION: SEND") < \
            c["query"].index("ACTION: CHECK-FIRST")
        assert send_first == (c["cluster"] % 2 == 0), c["case_id"]


def test_determinism():
    a = build(EVAL)
    b = build(EVAL)
    assert json.dumps(a) == json.dumps(b)
